/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'eth_nios_v2'
 * SOPC Builder design path: ../../eth_nios_v2.sopcinfo
 *
 * Generated: Wed Oct 09 15:29:18 MSK 2024
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00004820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 125000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0xf
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0x00002020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 125000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0xf
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00002000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00004820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 125000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0xf
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0x00002020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0xf
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00002000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_TIMER
#define __ALTERA_ETH_TSE
#define __ALTERA_NIOS2_GEN2


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone 10 LP"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x57a0
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x57a0
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x57a0
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "eth_nios_v2"


/*
 * eth_irq_pio configuration
 *
 */

#define ALT_MODULE_CLASS_eth_irq_pio altera_avalon_pio
#define ETH_IRQ_PIO_BASE 0x0
#define ETH_IRQ_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define ETH_IRQ_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ETH_IRQ_PIO_CAPTURE 1
#define ETH_IRQ_PIO_DATA_WIDTH 1
#define ETH_IRQ_PIO_DO_TEST_BENCH_WIRING 0
#define ETH_IRQ_PIO_DRIVEN_SIM_VALUE 0
#define ETH_IRQ_PIO_EDGE_TYPE "RISING"
#define ETH_IRQ_PIO_FREQ 125000000
#define ETH_IRQ_PIO_HAS_IN 1
#define ETH_IRQ_PIO_HAS_OUT 0
#define ETH_IRQ_PIO_HAS_TRI 0
#define ETH_IRQ_PIO_IRQ 4
#define ETH_IRQ_PIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ETH_IRQ_PIO_IRQ_TYPE "LEVEL"
#define ETH_IRQ_PIO_NAME "/dev/eth_irq_pio"
#define ETH_IRQ_PIO_RESET_VALUE 0
#define ETH_IRQ_PIO_SPAN 16
#define ETH_IRQ_PIO_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 4
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * header_ram configuration
 *
 */

#define ALT_MODULE_CLASS_header_ram altera_avalon_onchip_memory2
#define HEADER_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define HEADER_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define HEADER_RAM_BASE 0x5600
#define HEADER_RAM_CONTENTS_INFO ""
#define HEADER_RAM_DUAL_PORT 0
#define HEADER_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define HEADER_RAM_INIT_CONTENTS_FILE "eth_nios_v2_header_ram"
#define HEADER_RAM_INIT_MEM_CONTENT 1
#define HEADER_RAM_INSTANCE_ID "NONE"
#define HEADER_RAM_IRQ -1
#define HEADER_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEADER_RAM_NAME "/dev/header_ram"
#define HEADER_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define HEADER_RAM_RAM_BLOCK_TYPE "AUTO"
#define HEADER_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define HEADER_RAM_SINGLE_CLOCK_OP 0
#define HEADER_RAM_SIZE_MULTIPLE 1
#define HEADER_RAM_SIZE_VALUE 256
#define HEADER_RAM_SPAN 256
#define HEADER_RAM_TYPE "altera_avalon_onchip_memory2"
#define HEADER_RAM_WRITABLE 1


/*
 * header_ram configuration as viewed by tx_dma_m_read
 *
 */

#define TX_DMA_M_READ_HEADER_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define TX_DMA_M_READ_HEADER_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define TX_DMA_M_READ_HEADER_RAM_BASE 0x5600
#define TX_DMA_M_READ_HEADER_RAM_CONTENTS_INFO ""
#define TX_DMA_M_READ_HEADER_RAM_DUAL_PORT 0
#define TX_DMA_M_READ_HEADER_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define TX_DMA_M_READ_HEADER_RAM_INIT_CONTENTS_FILE "eth_nios_v2_header_ram"
#define TX_DMA_M_READ_HEADER_RAM_INIT_MEM_CONTENT 1
#define TX_DMA_M_READ_HEADER_RAM_INSTANCE_ID "NONE"
#define TX_DMA_M_READ_HEADER_RAM_IRQ -1
#define TX_DMA_M_READ_HEADER_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TX_DMA_M_READ_HEADER_RAM_NAME "/dev/header_ram"
#define TX_DMA_M_READ_HEADER_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define TX_DMA_M_READ_HEADER_RAM_RAM_BLOCK_TYPE "AUTO"
#define TX_DMA_M_READ_HEADER_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define TX_DMA_M_READ_HEADER_RAM_SINGLE_CLOCK_OP 0
#define TX_DMA_M_READ_HEADER_RAM_SIZE_MULTIPLE 1
#define TX_DMA_M_READ_HEADER_RAM_SIZE_VALUE 256
#define TX_DMA_M_READ_HEADER_RAM_SPAN 256
#define TX_DMA_M_READ_HEADER_RAM_TYPE "altera_avalon_onchip_memory2"
#define TX_DMA_M_READ_HEADER_RAM_WRITABLE 1


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x57a0
#define JTAG_UART_0_IRQ 2
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * rx_buf_ram configuration
 *
 */

#define ALT_MODULE_CLASS_rx_buf_ram altera_avalon_onchip_memory2
#define RX_BUF_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RX_BUF_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RX_BUF_RAM_BASE 0x5400
#define RX_BUF_RAM_CONTENTS_INFO ""
#define RX_BUF_RAM_DUAL_PORT 0
#define RX_BUF_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define RX_BUF_RAM_INIT_CONTENTS_FILE "eth_nios_v2_rx_buf_ram"
#define RX_BUF_RAM_INIT_MEM_CONTENT 1
#define RX_BUF_RAM_INSTANCE_ID "NONE"
#define RX_BUF_RAM_IRQ -1
#define RX_BUF_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RX_BUF_RAM_NAME "/dev/rx_buf_ram"
#define RX_BUF_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RX_BUF_RAM_RAM_BLOCK_TYPE "AUTO"
#define RX_BUF_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define RX_BUF_RAM_SINGLE_CLOCK_OP 0
#define RX_BUF_RAM_SIZE_MULTIPLE 1
#define RX_BUF_RAM_SIZE_VALUE 512
#define RX_BUF_RAM_SPAN 512
#define RX_BUF_RAM_TYPE "altera_avalon_onchip_memory2"
#define RX_BUF_RAM_WRITABLE 1


/*
 * rx_buf_ram configuration as viewed by rx_dma_m_write
 *
 */

#define RX_DMA_M_WRITE_RX_BUF_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RX_DMA_M_WRITE_RX_BUF_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RX_DMA_M_WRITE_RX_BUF_RAM_BASE 0x5400
#define RX_DMA_M_WRITE_RX_BUF_RAM_CONTENTS_INFO ""
#define RX_DMA_M_WRITE_RX_BUF_RAM_DUAL_PORT 0
#define RX_DMA_M_WRITE_RX_BUF_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define RX_DMA_M_WRITE_RX_BUF_RAM_INIT_CONTENTS_FILE "eth_nios_v2_rx_buf_ram"
#define RX_DMA_M_WRITE_RX_BUF_RAM_INIT_MEM_CONTENT 1
#define RX_DMA_M_WRITE_RX_BUF_RAM_INSTANCE_ID "NONE"
#define RX_DMA_M_WRITE_RX_BUF_RAM_IRQ -1
#define RX_DMA_M_WRITE_RX_BUF_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RX_DMA_M_WRITE_RX_BUF_RAM_NAME "/dev/rx_buf_ram"
#define RX_DMA_M_WRITE_RX_BUF_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RX_DMA_M_WRITE_RX_BUF_RAM_RAM_BLOCK_TYPE "AUTO"
#define RX_DMA_M_WRITE_RX_BUF_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define RX_DMA_M_WRITE_RX_BUF_RAM_SINGLE_CLOCK_OP 0
#define RX_DMA_M_WRITE_RX_BUF_RAM_SIZE_MULTIPLE 1
#define RX_DMA_M_WRITE_RX_BUF_RAM_SIZE_VALUE 512
#define RX_DMA_M_WRITE_RX_BUF_RAM_SPAN 512
#define RX_DMA_M_WRITE_RX_BUF_RAM_TYPE "altera_avalon_onchip_memory2"
#define RX_DMA_M_WRITE_RX_BUF_RAM_WRITABLE 1


/*
 * rx_dma configuration
 *
 */

#define ALT_MODULE_CLASS_rx_dma altera_avalon_sgdma
#define RX_DMA_ADDRESS_WIDTH 32
#define RX_DMA_ALWAYS_DO_MAX_BURST 1
#define RX_DMA_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define RX_DMA_AVALON_MM_BYTE_REORDER_MODE 0
#define RX_DMA_BASE 0x5700
#define RX_DMA_BURST_DATA_WIDTH 8
#define RX_DMA_BURST_TRANSFER 0
#define RX_DMA_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define RX_DMA_CHAIN_WRITEBACK_DATA_WIDTH 32
#define RX_DMA_COMMAND_FIFO_DATA_WIDTH 104
#define RX_DMA_CONTROL_DATA_WIDTH 8
#define RX_DMA_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define RX_DMA_CONTROL_SLAVE_DATA_WIDTH 32
#define RX_DMA_DESCRIPTOR_READ_BURST 0
#define RX_DMA_DESC_DATA_WIDTH 32
#define RX_DMA_HAS_READ_BLOCK 0
#define RX_DMA_HAS_WRITE_BLOCK 1
#define RX_DMA_IN_ERROR_WIDTH 1
#define RX_DMA_IRQ 0
#define RX_DMA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define RX_DMA_NAME "/dev/rx_dma"
#define RX_DMA_OUT_ERROR_WIDTH 0
#define RX_DMA_READ_BLOCK_DATA_WIDTH 8
#define RX_DMA_READ_BURSTCOUNT_WIDTH 4
#define RX_DMA_SPAN 64
#define RX_DMA_STATUS_TOKEN_DATA_WIDTH 24
#define RX_DMA_STREAM_DATA_WIDTH 8
#define RX_DMA_SYMBOLS_PER_BEAT 1
#define RX_DMA_TYPE "altera_avalon_sgdma"
#define RX_DMA_UNALIGNED_TRANSFER 0
#define RX_DMA_WRITE_BLOCK_DATA_WIDTH 8
#define RX_DMA_WRITE_BURSTCOUNT_WIDTH 4


/*
 * system_ram configuration
 *
 */

#define ALT_MODULE_CLASS_system_ram altera_avalon_onchip_memory2
#define SYSTEM_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SYSTEM_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SYSTEM_RAM_BASE 0x2000
#define SYSTEM_RAM_CONTENTS_INFO ""
#define SYSTEM_RAM_DUAL_PORT 0
#define SYSTEM_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define SYSTEM_RAM_INIT_CONTENTS_FILE "eth_nios_v2_system_ram"
#define SYSTEM_RAM_INIT_MEM_CONTENT 1
#define SYSTEM_RAM_INSTANCE_ID "NONE"
#define SYSTEM_RAM_IRQ -1
#define SYSTEM_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSTEM_RAM_NAME "/dev/system_ram"
#define SYSTEM_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SYSTEM_RAM_RAM_BLOCK_TYPE "AUTO"
#define SYSTEM_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SYSTEM_RAM_SINGLE_CLOCK_OP 0
#define SYSTEM_RAM_SIZE_MULTIPLE 1
#define SYSTEM_RAM_SIZE_VALUE 8191
#define SYSTEM_RAM_SPAN 8191
#define SYSTEM_RAM_TYPE "altera_avalon_onchip_memory2"
#define SYSTEM_RAM_WRITABLE 1


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_BASE 0x5780
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 125000000
#define TIMER_0_IRQ 3
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 124999
#define TIMER_0_MULT 8.0E-9
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 125000
#define TIMER_0_PERIOD_UNITS "clocks"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_SPAN 32
#define TIMER_0_TICKS_PER_SEC 1000
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"


/*
 * tse configuration
 *
 */

#define ALT_MODULE_CLASS_tse altera_eth_tse
#define TSE_BASE 0x5000
#define TSE_ENABLE_MACLITE 0
#define TSE_FIFO_WIDTH 8
#define TSE_IRQ -1
#define TSE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE_IS_MULTICHANNEL_MAC 0
#define TSE_MACLITE_GIGE 0
#define TSE_MDIO_SHARED 0
#define TSE_NAME "/dev/tse"
#define TSE_NUMBER_OF_CHANNEL 1
#define TSE_NUMBER_OF_MAC_MDIO_SHARED 1
#define TSE_PCS 0
#define TSE_PCS_ID 0
#define TSE_PCS_SGMII 0
#define TSE_RECEIVE_FIFO_DEPTH 128
#define TSE_REGISTER_SHARED 0
#define TSE_RGMII 1
#define TSE_SPAN 1024
#define TSE_TRANSMIT_FIFO_DEPTH 2048
#define TSE_TYPE "altera_eth_tse"
#define TSE_USE_MDIO 1


/*
 * tx_buff_ram configuration as viewed by tx_dma_m_read
 *
 */

#define TX_DMA_M_READ_TX_BUFF_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define TX_DMA_M_READ_TX_BUFF_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define TX_DMA_M_READ_TX_BUFF_RAM_BASE 0x0
#define TX_DMA_M_READ_TX_BUFF_RAM_CONTENTS_INFO ""
#define TX_DMA_M_READ_TX_BUFF_RAM_DUAL_PORT 1
#define TX_DMA_M_READ_TX_BUFF_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define TX_DMA_M_READ_TX_BUFF_RAM_INIT_CONTENTS_FILE "test"
#define TX_DMA_M_READ_TX_BUFF_RAM_INIT_MEM_CONTENT 1
#define TX_DMA_M_READ_TX_BUFF_RAM_INSTANCE_ID "NONE"
#define TX_DMA_M_READ_TX_BUFF_RAM_IRQ -1
#define TX_DMA_M_READ_TX_BUFF_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TX_DMA_M_READ_TX_BUFF_RAM_NAME "/dev/tx_buff_ram"
#define TX_DMA_M_READ_TX_BUFF_RAM_NON_DEFAULT_INIT_FILE_ENABLED 1
#define TX_DMA_M_READ_TX_BUFF_RAM_RAM_BLOCK_TYPE "AUTO"
#define TX_DMA_M_READ_TX_BUFF_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define TX_DMA_M_READ_TX_BUFF_RAM_SINGLE_CLOCK_OP 0
#define TX_DMA_M_READ_TX_BUFF_RAM_SIZE_MULTIPLE 1
#define TX_DMA_M_READ_TX_BUFF_RAM_SIZE_VALUE 2048
#define TX_DMA_M_READ_TX_BUFF_RAM_SPAN 2048
#define TX_DMA_M_READ_TX_BUFF_RAM_TYPE "altera_avalon_onchip_memory2"
#define TX_DMA_M_READ_TX_BUFF_RAM_WRITABLE 1


/*
 * tx_dma configuration
 *
 */

#define ALT_MODULE_CLASS_tx_dma altera_avalon_sgdma
#define TX_DMA_ADDRESS_WIDTH 32
#define TX_DMA_ALWAYS_DO_MAX_BURST 1
#define TX_DMA_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define TX_DMA_AVALON_MM_BYTE_REORDER_MODE 0
#define TX_DMA_BASE 0x5740
#define TX_DMA_BURST_DATA_WIDTH 8
#define TX_DMA_BURST_TRANSFER 0
#define TX_DMA_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define TX_DMA_CHAIN_WRITEBACK_DATA_WIDTH 32
#define TX_DMA_COMMAND_FIFO_DATA_WIDTH 104
#define TX_DMA_CONTROL_DATA_WIDTH 8
#define TX_DMA_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define TX_DMA_CONTROL_SLAVE_DATA_WIDTH 32
#define TX_DMA_DESCRIPTOR_READ_BURST 0
#define TX_DMA_DESC_DATA_WIDTH 32
#define TX_DMA_HAS_READ_BLOCK 1
#define TX_DMA_HAS_WRITE_BLOCK 0
#define TX_DMA_IN_ERROR_WIDTH 0
#define TX_DMA_IRQ 1
#define TX_DMA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TX_DMA_NAME "/dev/tx_dma"
#define TX_DMA_OUT_ERROR_WIDTH 1
#define TX_DMA_READ_BLOCK_DATA_WIDTH 8
#define TX_DMA_READ_BURSTCOUNT_WIDTH 4
#define TX_DMA_SPAN 64
#define TX_DMA_STATUS_TOKEN_DATA_WIDTH 24
#define TX_DMA_STREAM_DATA_WIDTH 8
#define TX_DMA_SYMBOLS_PER_BEAT 1
#define TX_DMA_TYPE "altera_avalon_sgdma"
#define TX_DMA_UNALIGNED_TRANSFER 0
#define TX_DMA_WRITE_BLOCK_DATA_WIDTH 8
#define TX_DMA_WRITE_BURSTCOUNT_WIDTH 4

#endif /* __SYSTEM_H_ */
